version: '0.0'

services:

  user:
    image: user:0.0.1-SNAPSHOT
    ports:
      - '6002:6002'

  registration:
    image: api:0.0.1-SNAPSHOT
    ports:
      - '6001:6001'

#services:
#  odyssey-api:
#    image: amazoncorretto:21
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'

#  database:
#    image: 'postgres:15.2'
#    ports:
#      - '5432'
#    environment:
#      - 'POSTGRES_USER=myuser'
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
